Steal all-job logic from `bittide/bittide-hardware`

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -137,15 +137,43 @@ jobs:
           # cabal v2-test
           cabal v2-run doctests
 
-
   # Mandatory check on GitHub
   all:
     name: All jobs finished
-    needs:
-      - cabal
-      - stack
-    runs-on: ubuntu-latest
+    if: always()
+    needs: [
+        cabal,
+        stack,
+      ]
+    runs-on: ubuntu-22.04
     steps:
-      - name: Void
+      - name: Checkout
+        uses: actions/checkout@v1
+
+      - name: Check dependencies for failures
         run: |
-          echo "All good"
+          # Test all dependencies for success/failure
+          set -x
+          success="${{ contains(needs.*.result, 'success') }}"
+          fail="${{ contains(needs.*.result, 'failure') }}"
+          set +x
+
+          # Test whether success/fail variables contain sane values
+          if [[ "${success}" != "true" && "${success}" != "false" ]]; then exit 1; fi
+          if [[ "${fail}"    != "true" && "${fail}"    != "false" ]]; then exit 1; fi
+
+          # We want to fail if one or more dependencies fail. For safety, we introduce
+          # a second check: if no dependencies succeeded something weird is going on.
+          if [[ "${fail}" == "true" || "${success}" == "false" ]]; then
+            echo "One or more dependency failed, or no dependency succeeded."
+            exit 1
+          fi
+
+      - name: Install dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get -y install python3-yaml
+
+      - name: Check that the 'all' job depends on all other jobs
+        run: |
+          .github/scripts/all_check.py
